openapi: 3.0.1
info:
  title: PetStoreAPI
  description: API Definition of PetStoreAPI
  version: 1.0.0
servers:
  - url: http://localhost:8290
paths:
  "/pet/list/{status}":
    get:
      responses:
        default:
          description: Default response
