---
openapi: 3.0.1
info:
  title: PetStoreAPI
  description: API Definition of PetStoreAPI
  version: 1.0.0
servers:
  - url: "http://localhost:8290/pet"
paths:
  "/list/{status}":
    get:
      parameters:
        - name: status
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      required:
      - id  
      - name
      - status
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: doggie
        status:
          type: string
          description: pet status in the store
          enum:
          - available
          - pending
          - sold




  
  